### ISSUE TITLE
Delete chart - Says couldn't delete after deleting it

### ISSUE THREAD

**Issue by dhanasiddharth** [senthilkumar2githup/Dashboard#49]
- Create column chart as described in https://github.com/senthilkumar2githup/Dashboard/issues/48
- Delete it
  Chart disappears from screen, and then says 'Couldn't delete the Chart'

Chart should not be removed from screen, until HIPIE successfully removes chart from the plugin. Confirmation dialog for Deleting chart is created using javascript alert. Instead ZK Confirmation dialog should be used.

**Comment by RajalakshmiElumalaiCts** [comment]
Added ZK message box to confirm delete action.Chart is removed after Hipie deletes it
